import os
import ninja_syntax
import glob
import subprocess

#Files compiled and automatically DMAed to expansion pak ram on boot
c_files = glob.glob('src/**/*.c', recursive=True)

# .s files are put into expansion pak ram and are *not* intended to have their headersize changed
s_files = glob.glob('asm/**/*.s', recursive=True)

# .asm files are assembly files that often change the headersize
asm_files = glob.glob('asm/**/*.asm', recursive=True)

def create_main_asm():
    header = f"""
// Automatically generated by configure.py, do not edit
.n64
.open "rom/{baseromName}", "rom/{romModName}", 0
"""

    footer = """
.align 8
PAYLOAD_END_RAM:
"""
    with open("asm/main.asm", 'w') as file:
        file.write(header)

        for asm_file in asm_files:
            if asm_file.endswith('main.asm'):
                continue
            file.write(f".include \"{asm_file}\"\n")

        file.write(".headersize 0x80400000 - 0x1F80000\n")

        file.write(f'.org 0x80400000\n')
        file.write('PAYLOAD_START_RAM:\n')

        for s_file in s_files:
            file.write(f".include \"{s_file}\"\n")

        for c_file in c_files:
            obj_file = os.path.join('obj', os.path.relpath(c_file, 'src')).replace('.c', '.o')
            file.write(f".importobj \"{obj_file}\"\n")

        file.write(footer)
        file.write(".headersize 0\n")
        file.write(".org 0x1FFFFFC\n")
        file.write(".word 0xDEADBEEF\n")
        file.write(".close\n")
        
        

def create_ninja_file(romModName, baseromName):
    c_flags = (
        "-O1 -Wall -Wno-missing-braces -mtune=vr4300 -march=vr4300 "
        "-mabi=32 -fomit-frame-pointer -mno-abicalls -fno-pic "
        "-fno-tree-loop-distribute-patterns -G0 -fno-inline "
        "-DF3DEX_GBI_2 -DDebug"
    )

    with open('build.ninja', 'w') as buildfile:
        ninja = ninja_syntax.Writer(buildfile)
        ninja.variable('CC', 'mips64-elf-gcc')
        ninja.variable('CFLAGS', c_flags)
        ninja.variable('INCLUDE_FLAGS', '-Iinclude -Isrc')

        # --------------------------
        # C COMPILATION RULE
        # --------------------------
        ninja.rule(
            "cc",
            command="$CC $CFLAGS $INCLUDE_FLAGS -c $in -o $out",
            description="Compiling $in to $out",
            depfile="$out.d",
            deps="gcc",
        )

        obj_files = []
        for c_file in c_files:
            obj_file = os.path.join('obj', os.path.relpath(c_file, 'src')).replace('.c', '.o')
            ninja.build(obj_file, 'cc', c_file)
            obj_files.append(obj_file)

        ninja.build('all', 'phony', obj_files)

        # --------------------------
        # ARMIPS RULE
        # --------------------------
        ninja.rule(
            "armips",
            command="armips asm/main.asm -sym syms.txt",
            description="Running armips on main.asm"
        )
        ninja.build('run_armips', 'armips', 'all')

        # --------------------------
        # N64CRC RULE
        # --------------------------
        ninja.rule(
            "n64crc",
            command=f"tools/n64crc.exe rom/{romModName}",
            description=f"Calculating CRC for {romModName}"
        )
        ninja.build('run_n64crc', 'n64crc', 'run_armips')

        # -----------------------------------------------------
        # CREATE PYTHON APPEND SCRIPT (WINDOWS SAFE)
        # -----------------------------------------------------
        append_script = r'''
import shutil

with open("rom/mp3-mod.z64", "ab") as out, open("rom/mp2.z64", "rb") as src:
    shutil.copyfileobj(src, out)
'''
        os.makedirs("tools", exist_ok=True)
        with open("tools/append_mp2.py", "w") as f:
            f.write(append_script)

        # -----------------------------------------------------
        # NINJA RULE: Append mp2.z64 onto mp3-mod.z64
        # -----------------------------------------------------
        ninja.rule(
            "append_mp2",
            command="python tools/append_mp2.py",
            description="Appending mp2.z64 to mp3-mod.z64"
        )

        ninja.build('run_append_mp2', 'append_mp2', 'run_n64crc')



if __name__ == "__main__":
    baseromName = "mp3-mainFS-repack.z64"
    romModName = "mp3-mod.z64"
    create_ninja_file(romModName, baseromName)
    create_main_asm()